------------------------thống kê khách hàng--------------------
go
create view ThongKeKhachHang AS
SELECT KH.TENKH,KH.SOCMND,PDK.NGAYTHUE,PDK.NGAYTRA,PT.TENPHONG
FROM KHACHHANG KH INNER JOIN PHIEUDANGKY PDK ON KH.MAKH = PDK.MAKH 
	 INNER JOIN PHONGTRO PT  ON PT.MAPHONG =  PDK.SOPHONG
go

select *from ThongKeKhachHang
------------------------Thống kê Trang bị Phòng---------------------
go
create view ThongKeTrangBiPhong AS
SELECT PT.TENPHONG,PT.HIENTRANGPHONG, TBi.TENTB
FROM TRANGBI TB INNER JOIN PHONGTRO PT ON TB.MAPHONG = PT.MAPHONG
		INNER JOIN THIETBI TBi ON TBi.MATB = TB.MATB
go
------------------------Thống kê Hóa Đơn---------------------
go
CREATE VIEW [dbo].[thongkeHoaDon]
AS
SELECT KHACHHANG.TENKH,KHACHHANG.SOCMND,PHONGTRO.TENPHONG,DICHVU.TENDV,PHIEUDANGKY.NGAYTHUE,PHIEUTHANHTOAN.TONGTIEN,HOADON.NGAYLAPHD 
FROM KHACHHANG inner join PHIEUDANGKY on KHACHHANG.MAKH=PHIEUDANGKY.MAKH inner join PHONGTRO on PHIEUDANGKY.SOPHONG=PHONGTRO.MAPHONG 
inner join DANGKY_DV on DANGKY_DV.MAPDK=PHIEUDANGKY.MAPDK inner join DICHVU on DICHVU.MADV=DANGKY_DV.MADV inner join PHIEUTHANHTOAN on PHIEUTHANHTOAN.MAPDK
= PHIEUDANGKY.MAPDK inner join HOADON on HOADON.MAPTT=PHIEUTHANHTOAN.MAPTT